name: Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies for Kivy and KivyMD
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          python3-dev \
          libssl-dev \
          libffi-dev \
          libjpeg-dev \
          libfreetype6-dev \
          libopenal-dev \
          libsndfile1 \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          zlib1g-dev \
          cython3 \
          ninja-build \
          libgtk-3-dev \
          android-sdk

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flet  # تثبيت مكتبة Flet
        pip install git+https://github.com/kivymd/KivyMD.git

    - name: Install Cython
      run: |
        python -m pip install Cython  # تثبيت Cython

    - name: Install setuptools
      run: |
          python -m pip install --upgrade setuptools

    - name: Install Kivy from GitHub
      run: |
        git clone https://github.com/kivy/kivy.git
        cd kivy
        python setup.py install

    - name: Install Flet CLI
      run: |
        curl -fsSL https://flet.dev/install | bash
        echo "export PATH=\"$HOME/.flet/bin:$PATH\"" >> $GITHUB_ENV
        
    - name: Install required dependencies for Linux build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        
    - name: Check adb version
      run: adb version

    - name: Install system dependencies for Kivy and KivyMD
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          python3-dev \
          libssl-dev \
          libffi-dev \
          libjpeg-dev \
          libfreetype6-dev \
          libopenal-dev \
          libsndfile1 \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          zlib1g-dev \
          cython3 \
          ninja-build \
          libgtk-3-dev

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Run Flutter doctor
      run: flutter doctor


    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flet Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: warn
        overwrite: false
